name: CICD

on:
     push:
          branches: [main, master]

jobs:
     build:
          runs-on: ubuntu-latest
          steps:
               - name: Checkout Source
                 uses: actions/checkout@v3

               - name: Login To Docker Hub
                 run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

               - name: Build Docker Image
                 run: docker build -t bkroland19/dash:nodeapp .

               - name: Push To Docker Hub
                 run: docker push bkroland19/dash:nodeapp

     deploy:
          needs: build
          runs-on: self-hosted
          steps:
               - name: Pull Image From Docker Hub
                 run: docker pull bkroland19/dash:nodeapp

               - name: Run Docker Container
                 run: docker run -d -p 5000:5000 bkroland19/dash:nodeapp
